#!/usr/bin/env python3
"""
Analyze the reasons for failure in parallel task scenarios
"""
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import networkx as nx

# Create figure
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# ========== Left: Incorrect result generated by LLM ==========
ax1.set_title("❌ Plan generated by LLM (Disconnected Graph)", fontsize=14, fontweight='bold', color='red')
ax1.set_xlim(0, 10)
ax1.set_ylim(0, 10)
ax1.axis('off')

# Draw two independent subgraphs
# Subgraph 1: Print task
ax1.add_patch(FancyBboxPatch((0.5, 6), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='blue', facecolor='lightblue', linewidth=2))
ax1.text(2, 6.75, 'Print Document', ha='center', va='center', fontsize=11, fontweight='bold')

ax1.add_patch(FancyBboxPatch((0.5, 3.5), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='blue', facecolor='lightblue', linewidth=2))
ax1.text(2, 4.25, 'Turn Off Printer', ha='center', va='center', fontsize=11, fontweight='bold')

# Arrow
arrow1 = FancyArrowPatch((2, 6), (2, 5), arrowstyle='->', lw=2, color='blue',
                         mutation_scale=20)
ax1.add_patch(arrow1)

# Subgraph 2: Email task (Independent!)
ax1.add_patch(FancyBboxPatch((6.5, 6), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='green', facecolor='lightgreen', linewidth=2))
ax1.text(8, 6.75, 'Send Email', ha='center', va='center', fontsize=11, fontweight='bold')

ax1.add_patch(FancyBboxPatch((6.5, 3.5), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='green', facecolor='lightgreen', linewidth=2))
ax1.text(8, 4.25, 'Turn On Computer', ha='center', va='center', fontsize=11, fontweight='bold')

# Arrow
arrow2 = FancyArrowPatch((8, 6), (8, 5), arrowstyle='->', lw=2, color='green',
                         mutation_scale=20)
ax1.add_patch(arrow2)

# Add warnings
ax1.text(5, 2, '⚠️ Two independent subgraphs!\nCannot find a unified execution order',
         ha='center', fontsize=12, color='red', fontweight='bold',
         bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

# Add disconnect mark
ax1.plot([4, 6], [5, 5], 'r--', linewidth=3, alpha=0.5)
ax1.text(5, 5.5, '❌ Disconnected', ha='center', fontsize=10, color='red', fontweight='bold')

# ========== Right: Correct structure ==========
ax2.set_title("✅ Correct Plan (Connected DAG)", fontsize=14, fontweight='bold', color='green')
ax2.set_xlim(0, 10)
ax2.set_ylim(0, 10)
ax2.axis('off')

# Start node
ax2.add_patch(FancyBboxPatch((3.5, 8.5), 3, 1, boxstyle="round,pad=0.1",
                              edgecolor='purple', facecolor='plum', linewidth=2))
ax2.text(5, 9, 'START (Virtual)', ha='center', va='center', fontsize=11, fontweight='bold')

# Parallel tasks
ax2.add_patch(FancyBboxPatch((0.5, 6), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='blue', facecolor='lightblue', linewidth=2))
ax2.text(2, 6.75, 'Print Document', ha='center', va='center', fontsize=11, fontweight='bold')

ax2.add_patch(FancyBboxPatch((6.5, 6), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='green', facecolor='lightgreen', linewidth=2))
ax2.text(8, 6.75, 'Send Email', ha='center', va='center', fontsize=11, fontweight='bold')

# Sync node
ax2.add_patch(FancyBboxPatch((3.5, 3.5), 3, 1.5, boxstyle="round,pad=0.1",
                              edgecolor='orange', facecolor='lightyellow', linewidth=2))
ax2.text(5, 4.25, 'Turn Off Printer\n(After both done)', ha='center', va='center',
         fontsize=10, fontweight='bold')

# Arrow: START -> Parallel tasks
arrow3 = FancyArrowPatch((4, 8.5), (2, 7.5), arrowstyle='->', lw=2, color='purple',
                         mutation_scale=20, connectionstyle="arc3,rad=0.3")
ax2.add_patch(arrow3)

arrow4 = FancyArrowPatch((6, 8.5), (8, 7.5), arrowstyle='->', lw=2, color='purple',
                         mutation_scale=20, connectionstyle="arc3,rad=-0.3")
ax2.add_patch(arrow4)

# Arrow: Parallel tasks -> Sync node
arrow5 = FancyArrowPatch((2, 6), (4, 5), arrowstyle='->', lw=2, color='blue',
                         mutation_scale=20, connectionstyle="arc3,rad=0.3")
ax2.add_patch(arrow5)

arrow6 = FancyArrowPatch((8, 6), (6, 5), arrowstyle='->', lw=2, color='green',
                         mutation_scale=20, connectionstyle="arc3,rad=-0.3")
ax2.add_patch(arrow6)

# Add description
ax2.text(5, 1.5, '✅ All nodes connected!\nHas explicit Join Point',
         ha='center', fontsize=12, color='green', fontweight='bold',
         bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.7))

plt.suptitle('Parallel Task Scenario Failure Analysis', fontsize=16, fontweight='bold', y=0.98)
plt.tight_layout()
plt.savefig('parallel_task_failure_analysis.png', dpi=300, bbox_inches='tight')
print("✅ Visualization saved to: parallel_task_failure_analysis.png")

# Create second plot: NetworkX diagram
fig2, (ax3, ax4) = plt.subplots(1, 2, figsize=(14, 6))

# Wrong graph
G_wrong = nx.DiGraph()
G_wrong.add_edges_from([
    ('Print', 'TurnOffPrinter'),
    ('TurnOnComputer', 'SendEmail')
])

pos_wrong = {
    'Print': (0, 1),
    'TurnOffPrinter': (0, 0),
    'TurnOnComputer': (2, 1),
    'SendEmail': (2, 0)
}

nx.draw(G_wrong, pos_wrong, ax=ax3, with_labels=True, node_color='lightcoral',
        node_size=3000, font_size=9, font_weight='bold', arrows=True,
        arrowsize=20, edge_color='red', width=2)
ax3.set_title('❌ Error: 2 Independent Subgraphs\n(Disconnected)', fontsize=12, fontweight='bold', color='red')

# Check connectivity
num_components = nx.number_weakly_connected_components(G_wrong)
ax3.text(1, -0.8, f'Number of weakly connected components: {num_components}\nTopological sort: Impossible ❌',
         ha='center', fontsize=10,
         bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

# Correct graph
G_correct = nx.DiGraph()
G_correct.add_edges_from([
    ('START', 'Print'),
    ('START', 'SendEmail'),
    ('Print', 'TurnOffPrinter'),
    ('SendEmail', 'TurnOffPrinter')
])

pos_correct = {
    'START': (1, 2),
    'Print': (0, 1),
    'SendEmail': (2, 1),
    'TurnOffPrinter': (1, 0)
}

nx.draw(G_correct, pos_correct, ax=ax4, with_labels=True, node_color='lightgreen',
        node_size=3000, font_size=9, font_weight='bold', arrows=True,
        arrowsize=20, edge_color='green', width=2)
ax4.set_title('✅ Correct: 1 Connected DAG\n(Connected)', fontsize=12, fontweight='bold', color='green')

# Topological sort
topo_order = list(nx.topological_sort(G_correct))
ax4.text(1, -0.8, f'Number of weakly connected components: 1\nTopological sort: {" -> ".join(topo_order)}',
         ha='center', fontsize=9,
         bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.7))

plt.suptitle('Graph Theory Perspective: Connectivity Check', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('graph_connectivity_analysis.png', dpi=300, bbox_inches='tight')
print("✅ Graph analysis saved to: graph_connectivity_analysis.png")
